fix:
  sessions:
    - sessionId: "FIX.4.4:GTWY->BANZ"
      type: "ACCEPTOR"
      senderCompId: "GTWY"
      targetCompId: "BANZ"
      host: "0.0.0.0"
      port: 9881
      fixVersion: "FIX.4.4"
      dictionary: "FIX44.xml"
      enabled: true
      heartbeatInterval: 30
      resetOnLogon: true
      resetOnLogout: true
      resetOnDisconnect: true
      inputPartitions: 1
      partitionStrategy: KEY
      partitionExpression: |
        Symbol
      
    - sessionId: "FIX.4.4:GTWY->EXEC"
      type: "INITIATOR"
      senderCompId: "GTWY"
      targetCompId: "EXEC"
      host: "localhost"
      port: 9880
      fixVersion: "FIX.4.4"
      dictionary: "FIX44.xml"
      enabled: true
      heartbeatInterval: 30
      resetOnLogon: true
      resetOnLogout: true
      resetOnDisconnect: true
      partitionStrategy: KEY
      partitionExpression: |
        Symbol
      
    - sessionId: "FIX.4.4:GTWY->HEDGE"
      type: "INITIATOR"
      senderCompId: "GTWY"
      targetCompId: "HEDGE"
      host: "localhost"
      port: 9876
      fixVersion: "FIX.4.4"
      dictionary: "FIX44.xml"
      enabled: true
      heartbeatInterval: 30
      resetOnLogon: true
      resetOnLogout: true
      resetOnDisconnect: true
      partitionStrategy: KEY
      partitionExpression: |
        Symbol

 
#      if (MsgType == "D") {
#         return 1;
#       } else if (MsgType == "8") {
#         return 0;
#       } else {
#         return 2;
#       }
          
 
      
